import type { ItemGoal, FinanceGoal, ActionGoal, Goal, User } from '@/types/goals';

export const mockItemGoals: ItemGoal[] = [
  {
    id: 'item-1',
    type: 'item',
    title: 'Sony WH-1000XM5 Headphones',
    description: 'Premium noise-canceling wireless headphones for work and travel',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
    status: 'active',
    productImage: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&h=400&fit=crop',
    bestPrice: 328.00,
    currency: 'USD',
    retailerUrl: 'https://amazon.com',
    retailerName: 'Amazon',
    statusBadge: 'price-drop',
  },
  {
    id: 'item-2',
    type: 'item',
    title: 'MacBook Pro 14" M3',
    description: 'New laptop for development work',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-22'),
    status: 'active',
    productImage: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop',
    bestPrice: 1999.00,
    currency: 'USD',
    retailerUrl: 'https://apple.com',
    retailerName: 'Apple',
    statusBadge: 'in-stock',
  },
  {
    id: 'item-3',
    type: 'item',
    title: 'Herman Miller Aeron Chair',
    description: 'Ergonomic office chair for home setup',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-18'),
    status: 'active',
    productImage: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400&h=400&fit=crop',
    bestPrice: 1395.00,
    currency: 'USD',
    retailerUrl: 'https://hermanmiller.com',
    retailerName: 'Herman Miller',
    statusBadge: 'pending-search',
  },
];

export const mockFinanceGoals: FinanceGoal[] = [
  {
    id: 'finance-1',
    type: 'finance',
    title: 'Emergency Fund',
    description: '6 months of expenses saved for emergencies',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-25'),
    status: 'active',
    institutionIcon: '🏦',
    accountName: 'High-Yield Savings',
    currentBalance: 12500.00,
    targetBalance: 25000.00,
    currency: 'USD',
    progressHistory: [8000, 9200, 10100, 10800, 11200, 11800, 12100, 12500],
    lastSync: new Date('2024-01-25'),
  },
  {
    id: 'finance-2',
    type: 'finance',
    title: 'Vacation Fund',
    description: 'Japan trip summer 2024',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-24'),
    status: 'active',
    institutionIcon: '✈️',
    accountName: 'Travel Savings',
    currentBalance: 3200.00,
    targetBalance: 5000.00,
    currency: 'USD',
    progressHistory: [1500, 1800, 2100, 2400, 2700, 2900, 3100, 3200],
    lastSync: new Date('2024-01-24'),
  },
  {
    id: 'finance-3',
    type: 'finance',
    title: 'Investment Portfolio',
    description: 'Long-term wealth building',
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2024-01-25'),
    status: 'active',
    institutionIcon: '📈',
    accountName: 'Brokerage Account',
    currentBalance: 45200.00,
    targetBalance: 100000.00,
    currency: 'USD',
    progressHistory: [38000, 39500, 41000, 42200, 43800, 44100, 44800, 45200],
    lastSync: new Date('2024-01-25'),
  },
];

export const mockActionGoals: ActionGoal[] = [
  {
    id: 'action-1',
    type: 'action',
    title: 'Learn TypeScript',
    description: 'Master TypeScript for better React development',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-23'),
    status: 'active',
    completionPercentage: 60,
    tasks: [
      { id: 't1', title: 'Complete TypeScript fundamentals course', completed: true, createdAt: new Date() },
      { id: 't2', title: 'Practice with 5 coding challenges', completed: true, createdAt: new Date() },
      { id: 't3', title: 'Build a small project with TypeScript', completed: true, createdAt: new Date() },
      { id: 't4', title: 'Learn advanced types and generics', completed: false, createdAt: new Date() },
      { id: 't5', title: 'Contribute to an open source TS project', completed: false, createdAt: new Date() },
    ],
  },
  {
    id: 'action-2',
    type: 'action',
    title: 'Morning Routine',
    description: 'Build a consistent morning routine for productivity',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-25'),
    status: 'active',
    completionPercentage: 75,
    tasks: [
      { id: 't6', title: 'Wake up at 6:30 AM consistently', completed: true, createdAt: new Date() },
      { id: 't7', title: '10 min meditation', completed: true, createdAt: new Date() },
      { id: 't8', title: '20 min exercise', completed: true, createdAt: new Date() },
      { id: 't9', title: 'No phone for first hour', completed: false, createdAt: new Date() },
    ],
  },
  {
    id: 'action-3',
    type: 'action',
    title: 'Read 12 Books This Year',
    description: 'Expand knowledge through consistent reading',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-20'),
    status: 'active',
    completionPercentage: 17,
    tasks: [
      { id: 't10', title: 'Atomic Habits - James Clear', completed: true, createdAt: new Date() },
      { id: 't11', title: 'Deep Work - Cal Newport', completed: true, createdAt: new Date() },
      { id: 't12', title: 'The Psychology of Money', completed: false, createdAt: new Date() },
      { id: 't13', title: 'Thinking, Fast and Slow', completed: false, createdAt: new Date() },
      { id: 't14', title: 'The Lean Startup', completed: false, createdAt: new Date() },
      { id: 't15', title: 'Sapiens', completed: false, createdAt: new Date() },
    ],
  },
];

export const mockGoals: Goal[] = [
  ...mockItemGoals,
  ...mockFinanceGoals,
  ...mockActionGoals,
];

export const mockUser: User = {
  id: 'user-1',
  name: 'Alex Chen',
  email: 'alex@example.com',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
};
