name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /var/www/Neon-Goals-UI
          git fetch origin
          git reset --hard origin/main
          bun install --frozen-lockfile
          bun run db:generate
          bun run build
